### ISSUE TITLE
Snap package ready and in the store

### ISSUE THREAD

**Issue by soumyaDghosh** [mufeedali/Wordbook#49]
Hii, I have made a snap package for your app. Would you like to have it as official?

**Comment by mufeedali** [comment]
Hi! That's really cool! I want to add it as an unofficial install method. Hope I can ping you for any snap-specific issues?

**Comment by soumyaDghosh** [comment]
Need your help to fix the latest 0.4.0 release. Also, you can ping me.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/wordbook/current/usr/share/wordbook/wordbook/window.py", line 561, in _try_dl_wn
    self._wn_downloader.download(ProgressUpdater)
  File "/snap/wordbook/current/usr/share/wordbook/wordbook/base.py", line 345, in download
    wn.download(WN_DB_VERSION, progress_handler=progress_handler)
  File "/snap/wordbook/15/usr/lib/python3/dist-packages/wn/_download.py", line 57, in download
    info = config.get_project_info(project_or_url)
  File "/snap/wordbook/15/usr/lib/python3/dist-packages/wn/_config.py", line 130, in get_project_info
    project: Dict = self._projects[id]
KeyError: 'oewn'
```

**Comment by mufeedali** [comment]
My guess would be that your wn python module is outdated.

**Comment by soumyaDghosh** [comment]
Thanks fixed the snap again. 

> Hi! That's really cool! I want to add it as an unofficial install method. Hope I can ping you for any snap-specific issues?

Sure you can. Would very much appreciate if you take this as an official package. It already has 216 Active Users.

**Comment by mufeedali** [comment]
> Would very much appreciate if you take this as an official package.

I'm sorry but I can't since I don't use Ubuntu or any derivative. But as I said, I will add it in the Readme and such.

**Comment by soumyaDghosh** [comment]
```
<a href="https://snapcraft.io/wordbook">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>
```
Add this to publicise.

BTW, you can install snapd in any distro.

**Comment by mufeedali** [comment]
> BTW, you can install snapd in any distro.

I'm aware. I just believe Flatpak to be the way to go for an app like mine. And as you can guess from the pace of updates and all, I don't really have the ability to set aside more time for package maintenance. :(

> Add this to publicise.

Will do! Thanks!

**Comment by soumyaDghosh** [comment]
> I'm aware. I just believe Flatpak to be the way to go for an app like mine. And as you can guess from the pace of updates and all, I don't really have the ability to set aside more time for package maintenance. :(

You can leave that part on me. Anyway, it doesn't need too much of changes.

**Comment by mufeedali** [comment]
> Anyway, it doesn't need too much of changes.

The thing is, it might in the future and it did in the past. Currently I'm not getting much time to update stuff. But if I did, you would be having a lot of moving parts always.

**Comment by soumyaDghosh** [comment]
> The thing is, it might in the future and it did in the past. Currently I'm not getting much time to update stuff. But if I did, you would be having a lot of moving parts always.

No worries. Closing this issue then as not planned.
