### ISSUE TITLE
App not starting/opening on Fedora 37, GNOME 43.8

### ISSUE THREAD

**Issue by ArcticDev78** [mufeedali/Wordbook#53]
* Wordbook version: 0.4.0
* Python version: Python 3.11.5
* Operating System: Fedora Linux 37 (Workstation Edition)
* (Extra OS Info): Kernel is **6.0.7-301.fc37.x86_64** and GNOME version is **GNOME 43.8**

### Description

After a recent update, I tried opening the Wordbook app as usual but it never seemed to open. Could this be because I'm using an outdated version of Fedora, GNOME or the Linux Kernel?

### What I Did

I tried running it in the terminal using the following command: and this is the output I got:
```
flatpak run dev.mufeed.Wordbook --verbose
```
![Screenshot](https://github.com/mufeedali/Wordbook/assets/131583057/e1ad6ce2-44ab-485d-9807-ec9b7ae0a5df)

**Comment by D0-0K** [comment]
Seconding this issue, I had this problem on the latest version of Fedora too.

Attempted a fresh install of Wordbook, removing all folders associated with the flatpak. It allowed the app to boot, but it got stuck on the setup screen at the "Reading /tmp/tmp3z83wzuk.xml" part. Completely freezed the app, and the system attempted to force quit. 

I left it for a short while, and the progress bar did actually increase. On a whim I turned on performance mode, and Wordbook immediately kicked to life and completed the process and booted into the main app.

![image](https://github.com/mufeedali/Wordbook/assets/66568057/0bc5f66b-c59f-45c6-9cdc-a83fbf7c2a4f)

**Comment by mufeedali** [comment]
> Could this be because I'm using an outdated version of Fedora, GNOME or the Linux Kernel?

Don't worry, it's none of those, it's my mistake. Could you clear the application data for Wordbook as a workaround?

**Comment by ArcticDev78** [comment]
> Don't worry, it's none of those, it's my mistake. Could you clear the application data for Wordbook as a workaround?

Okay, so I uninstalled the app (flatpak) through the GNOME Software app and I used Flatsweep to clear the application's data, and the app opened, showed the same thing shown in @D0-0K's screenshot above and after some time the app finally worked! :tada: 
Thank you so much for your help @mufeedali and @D0-0K !
