### ISSUE TITLE
Enhancement: Add "Search selected text" option to the mouse context menu

### ISSUE THREAD

**Issue by TriVoxel** [mufeedali/Wordbook#55]
I noticed there is a feature to "Search selected text" which can be done with <kbd>Ctrl</kbd>+<kbd>S</kbd>, or optionaly with double-click in Preferences. I think if you added the option to the mouse right click context menu, it would make it a lot more accessible to the average user.

![Screenshot_from_2023-10-15_03-39-10](https://gitlab.com/mufeedali/Wordbook/uploads/c89a91e63b20068aa10a9f9ed16cf7e6/Screenshot_from_2023-10-15_03-39-10.png)

**Comment by mufeedali** [comment]
Need to look into if this is actually possible. Will implement if so :)

**Comment by gullmar** [comment]
Maybe it would be easier to implement a command line argument, e.g.: `-s`, to search the selected word as soon as the program opens. In this way, a user could create a keyboard shortcut like `wordbook -s` to quickly search for the currently selected text.
