### ISSUE TITLE
Nix package not mentioned in README

### ISSUE THREAD

**Issue by ann4n** [mufeedali/Wordbook#68]
[Using distro-specific packages](https://github.com/mufeedali/Wordbook?tab=readme-ov-file#using-distro-specific-packages) section doesn't mention Wordbook being [packaged in nixpkgs](https://search.nixos.org/packages?channel=unstable&show=wordbook&from=0&size=50&sort=relevance&type=packages&query=wordbook).

**Comment by mufeedali** [comment]
Regarding that part of the README, I'm hoping that the package maintainers or other users would submit a PR if they notice a package is maintained for Wordbook

**Comment by ann4n** [comment]
[pull request](https://github.com/mufeedali/Wordbook/pull/69)
