### ISSUE TITLE
Wrong pronunciation for word "over"

### ISSUE THREAD

**Issue by dimdin** [mufeedali/Wordbook#70]
* Wordbook version: 0.4.0 (from flatpak)

### Description

Pressed "Listen to Pronunciation" for the word "over".
The produced IPA for the word is correct: /ˈoʊvɚ/
The word played is "omer", I was expecting to listen "over".

**Comment by mufeedali** [comment]
I'm unable to reproduce this :(

Please re-open if you can still reproduce this
